services:
  app:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - DATABASE=mongodb://admin:admin@mongodb:27017/pixelbattle?authSource=admin
    depends_on:
      mongodb:
        condition: service_healthy

  mongodb:
    image: mongo:8
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
